name: docker
on: push

jobs:
  image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub authentication
        uses: docker/login-action@v1
        with:
          username: figtive
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Parse semver string
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: build and push versioned image
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          cache-from: figtive/gallery-dashboard:latest
          tags: |
            figtive/gallery-dashboard:latest
            figtive/gallery-dashboard:${{ github.sha }}
            figtive/gallery-dashboard:${{ steps.semver_parser.outputs.major }}
            figtive/gallery-dashboard:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            figtive/gallery-dashboard:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
      - name: build and push nightly image
        if: ${{ startsWith(github.ref, 'refs/heads') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          cache-from: figtive/gallery-dashboard:nightly
          tags: |
            figtive/gallery-dashboard:nightly
            figtive/gallery-dashboard:${{ github.sha }}
